name: Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
    steps:
      - name: copia os arquivos do repositório
        uses: actions/checkout@v3
        
      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Instalar o pipx
        run: python -m pip install --user pipx
          
      - name: Instalar o poetry
        run: pipx install poetry

      - name: Verificar diretório de trabalho
        run: pwd

      - name: Listar arquivos no diretório
        run: ls -la

      - name: Instalar dependências
        run: poetry install
        working-directory: .

      - name: Executar testes
        run: poetry run task test
        working-directory: .



        
